<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso_code' => 'AF', 'dialing_code' => '+93'],
            ['name' => 'Albania', 'iso_code' => 'AL', 'dialing_code' => '+355'],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'dialing_code' => '+213'],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'dialing_code' => '+376'],
            ['name' => 'Angola', 'iso_code' => 'AO', 'dialing_code' => '+244'],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'AG', 'dialing_code' => '+1-268'],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'dialing_code' => '+54'],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'dialing_code' => '+374'],
            ['name' => 'Australia', 'iso_code' => 'AU', 'dialing_code' => '+61'],
            ['name' => 'Austria', 'iso_code' => 'AT', 'dialing_code' => '+43'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'dialing_code' => '+994'],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'dialing_code' => '+1-242'],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'dialing_code' => '+973'],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'dialing_code' => '+880'],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'dialing_code' => '+1-246'],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'dialing_code' => '+375'],
            ['name' => 'Belgium', 'iso_code' => 'BE', 'dialing_code' => '+32'],
            ['name' => 'Belize', 'iso_code' => 'BZ', 'dialing_code' => '+501'],
            ['name' => 'Benin', 'iso_code' => 'BJ', 'dialing_code' => '+229'],
            ['name' => 'Bhutan', 'iso_code' => 'BT', 'dialing_code' => '+975'],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'dialing_code' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'dialing_code' => '+387'],
            ['name' => 'Botswana', 'iso_code' => 'BW', 'dialing_code' => '+267'],
            ['name' => 'Brazil', 'iso_code' => 'BR', 'dialing_code' => '+55'],
            ['name' => 'Brunei', 'iso_code' => 'BN', 'dialing_code' => '+673'],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'dialing_code' => '+359'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'dialing_code' => '+226'],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'dialing_code' => '+257'],
            ['name' => 'Cabo Verde', 'iso_code' => 'CV', 'dialing_code' => '+238'],
            ['name' => 'Cambodia', 'iso_code' => 'KH', 'dialing_code' => '+855'],
            ['name' => 'Cameroon', 'iso_code' => 'CM', 'dialing_code' => '+237'],
            ['name' => 'Canada', 'iso_code' => 'CA', 'dialing_code' => '+1'],
            ['name' => 'Central African Republic', 'iso_code' => 'CF', 'dialing_code' => '+236'],
            ['name' => 'Chad', 'iso_code' => 'TD', 'dialing_code' => '+235'],
            ['name' => 'Chile', 'iso_code' => 'CL', 'dialing_code' => '+56'],
            ['name' => 'China', 'iso_code' => 'CN', 'dialing_code' => '+86'],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'dialing_code' => '+57'],
            ['name' => 'Comoros', 'iso_code' => 'KM', 'dialing_code' => '+269'],
            ['name' => 'Congo (Congo-Brazzaville)', 'iso_code' => 'CG', 'dialing_code' => '+242'],
            ['name' => 'Congo (Democratic Republic)', 'iso_code' => 'CD', 'dialing_code' => '+243'],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'dialing_code' => '+506'],
            ['name' => 'Croatia', 'iso_code' => 'HR', 'dialing_code' => '+385'],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'dialing_code' => '+53'],
            ['name' => 'Cyprus', 'iso_code' => 'CY', 'dialing_code' => '+357'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZ', 'dialing_code' => '+420'],
            ['name' => 'Denmark', 'iso_code' => 'DK', 'dialing_code' => '+45'],
            ['name' => 'Djibouti', 'iso_code' => 'DJ', 'dialing_code' => '+253'],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'dialing_code' => '+1-767'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'dialing_code' => '+1-809'],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'dialing_code' => '+593'],
            ['name' => 'Egypt', 'iso_code' => 'EG', 'dialing_code' => '+20'],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'dialing_code' => '+503'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GQ', 'dialing_code' => '+240'],
            ['name' => 'Eritrea', 'iso_code' => 'ER', 'dialing_code' => '+291'],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'dialing_code' => '+372'],
            ['name' => 'Eswatini', 'iso_code' => 'SZ', 'dialing_code' => '+268'],
            ['name' => 'Ethiopia', 'iso_code' => 'ET', 'dialing_code' => '+251'],
            ['name' => 'Fiji', 'iso_code' => 'FJ', 'dialing_code' => '+679'],
            ['name' => 'Finland', 'iso_code' => 'FI', 'dialing_code' => '+358'],
            ['name' => 'France', 'iso_code' => 'FR', 'dialing_code' => '+33'],
            ['name' => 'Gabon', 'iso_code' => 'GA', 'dialing_code' => '+241'],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'dialing_code' => '+220'],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'dialing_code' => '+995'],
            ['name' => 'Germany', 'iso_code' => 'DE', 'dialing_code' => '+49'],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'dialing_code' => '+233'],
            ['name' => 'Greece', 'iso_code' => 'GR', 'dialing_code' => '+30'],
            ['name' => 'Grenada', 'iso_code' => 'GD', 'dialing_code' => '+1-473'],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'dialing_code' => '+502'],
            ['name' => 'Guinea', 'iso_code' => 'GN', 'dialing_code' => '+224'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GW', 'dialing_code' => '+245'],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'dialing_code' => '+592'],
            ['name' => 'Haiti', 'iso_code' => 'HT', 'dialing_code' => '+509'],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'dialing_code' => '+504'],
            ['name' => 'Hungary', 'iso_code' => 'HU', 'dialing_code' => '+36'],
            ['name' => 'Iceland', 'iso_code' => 'IS', 'dialing_code' => '+354'],
            ['name' => 'India', 'iso_code' => 'IN', 'dialing_code' => '+91'],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'dialing_code' => '+62'],
            ['name' => 'Iran', 'iso_code' => 'IR', 'dialing_code' => '+98'],
            ['name' => 'Iraq', 'iso_code' => 'IQ', 'dialing_code' => '+964'],
            ['name' => 'Ireland', 'iso_code' => 'IE', 'dialing_code' => '+353'],
            ['name' => 'Israel', 'iso_code' => 'IL', 'dialing_code' => '+972'],
            ['name' => 'Italy', 'iso_code' => 'IT', 'dialing_code' => '+39'],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'dialing_code' => '+1-876'],
            ['name' => 'Japan', 'iso_code' => 'JP', 'dialing_code' => '+81'],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'dialing_code' => '+962'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KZ', 'dialing_code' => '+7'],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'dialing_code' => '+254'],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'dialing_code' => '+686'],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'dialing_code' => '+965'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KG', 'dialing_code' => '+996'],
            ['name' => 'Laos', 'iso_code' => 'LA', 'dialing_code' => '+856'],
            ['name' => 'Latvia', 'iso_code' => 'LV', 'dialing_code' => '+371'],
            ['name' => 'Lebanon', 'iso_code' => 'LB', 'dialing_code' => '+961'],
            ['name' => 'Lesotho', 'iso_code' => 'LS', 'dialing_code' => '+266'],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'dialing_code' => '+231'],
            ['name' => 'Libya', 'iso_code' => 'LY', 'dialing_code' => '+218'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'dialing_code' => '+423'],
            ['name' => 'Lithuania', 'iso_code' => 'LT', 'dialing_code' => '+370'],
            ['name' => 'Luxembourg', 'iso_code' => 'LU', 'dialing_code' => '+352'],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'dialing_code' => '+261'],
            ['name' => 'Malawi', 'iso_code' => 'MW', 'dialing_code' => '+265'],
            ['name' => 'Malaysia', 'iso_code' => 'MY', 'dialing_code' => '+60'],
            ['name' => 'Maldives', 'iso_code' => 'MV', 'dialing_code' => '+960'],
            ['name' => 'Mali', 'iso_code' => 'ML', 'dialing_code' => '+223'],
            ['name' => 'Malta', 'iso_code' => 'MT', 'dialing_code' => '+356'],
            ['name' => 'Marshall Islands', 'iso_code' => 'MH', 'dialing_code' => '+692'],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'dialing_code' => '+222'],
            ['name' => 'Mauritius', 'iso_code' => 'MU', 'dialing_code' => '+230'],
            ['name' => 'Mexico', 'iso_code' => 'MX', 'dialing_code' => '+52'],
            ['name' => 'Micronesia', 'iso_code' => 'FM', 'dialing_code' => '+691'],
            ['name' => 'Moldova', 'iso_code' => 'MD', 'dialing_code' => '+373'],
            ['name' => 'Monaco', 'iso_code' => 'MC', 'dialing_code' => '+377'],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'dialing_code' => '+976'],
            ['name' => 'Montenegro', 'iso_code' => 'ME', 'dialing_code' => '+382'],
            ['name' => 'Morocco', 'iso_code' => 'MA', 'dialing_code' => '+212'],
            ['name' => 'Mozambique', 'iso_code' => 'MZ', 'dialing_code' => '+258'],
            ['name' => 'Myanmar (Burma)', 'iso_code' => 'MM', 'dialing_code' => '+95'],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'dialing_code' => '+264'],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'dialing_code' => '+674'],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'dialing_code' => '+977'],
            ['name' => 'Netherlands', 'iso_code' => 'NL', 'dialing_code' => '+31'],
            ['name' => 'New Zealand', 'iso_code' => 'NZ', 'dialing_code' => '+64'],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'dialing_code' => '+505'],
            ['name' => 'Niger', 'iso_code' => 'NE', 'dialing_code' => '+227'],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'dialing_code' => '+234'],
            ['name' => 'North Korea', 'iso_code' => 'KP', 'dialing_code' => '+850'],
            ['name' => 'North Macedonia', 'iso_code' => 'MK', 'dialing_code' => '+389'],
            ['name' => 'Norway', 'iso_code' => 'NO', 'dialing_code' => '+47'],
            ['name' => 'Oman', 'iso_code' => 'OM', 'dialing_code' => '+968'],
            ['name' => 'Pakistan', 'iso_code' => 'PK', 'dialing_code' => '+92'],
            ['name' => 'Palau', 'iso_code' => 'PW', 'dialing_code' => '+680'],
            ['name' => 'Palestine', 'iso_code' => 'PS', 'dialing_code' => '+970'],
            ['name' => 'Panama', 'iso_code' => 'PA', 'dialing_code' => '+507'],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PG', 'dialing_code' => '+675'],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'dialing_code' => '+595'],
            ['name' => 'Peru', 'iso_code' => 'PE', 'dialing_code' => '+51'],
            ['name' => 'Philippines', 'iso_code' => 'PH', 'dialing_code' => '+63'],
            ['name' => 'Poland', 'iso_code' => 'PL', 'dialing_code' => '+48'],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'dialing_code' => '+351'],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'dialing_code' => '+974'],
            ['name' => 'Romania', 'iso_code' => 'RO', 'dialing_code' => '+40'],
            ['name' => 'Russia', 'iso_code' => 'RU', 'dialing_code' => '+7'],
            ['name' => 'Rwanda', 'iso_code' => 'RW', 'dialing_code' => '+250'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KN', 'dialing_code' => '+1-869'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LC', 'dialing_code' => '+1-758'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VC', 'dialing_code' => '+1-784'],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'dialing_code' => '+685'],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'dialing_code' => '+378'],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'ST', 'dialing_code' => '+239'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'dialing_code' => '+966'],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'dialing_code' => '+221'],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'dialing_code' => '+381'],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'dialing_code' => '+248'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SL', 'dialing_code' => '+232'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'dialing_code' => '+65'],
            ['name' => 'Slovakia', 'iso_code' => 'SK', 'dialing_code' => '+421'],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'dialing_code' => '+386'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SB', 'dialing_code' => '+677'],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'dialing_code' => '+252'],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'dialing_code' => '+27'],
            ['name' => 'South Korea', 'iso_code' => 'KR', 'dialing_code' => '+82'],
            ['name' => 'South Sudan', 'iso_code' => 'SS', 'dialing_code' => '+211'],
            ['name' => 'Spain', 'iso_code' => 'ES', 'dialing_code' => '+34'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'dialing_code' => '+94'],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'dialing_code' => '+249'],
            ['name' => 'Suriname', 'iso_code' => 'SR', 'dialing_code' => '+597'],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'dialing_code' => '+46'],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'dialing_code' => '+41'],
            ['name' => 'Syria', 'iso_code' => 'SY', 'dialing_code' => '+963'],
            ['name' => 'Taiwan', 'iso_code' => 'TW', 'dialing_code' => '+886'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJ', 'dialing_code' => '+992'],
            ['name' => 'Tanzania', 'iso_code' => 'TZ', 'dialing_code' => '+255'],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'dialing_code' => '+66'],
            ['name' => 'Timor-Leste', 'iso_code' => 'TL', 'dialing_code' => '+670'],
            ['name' => 'Togo', 'iso_code' => 'TG', 'dialing_code' => '+228'],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'dialing_code' => '+676'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TT', 'dialing_code' => '+1-868'],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'dialing_code' => '+216'],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'dialing_code' => '+90'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TM', 'dialing_code' => '+993'],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'dialing_code' => '+688'],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'dialing_code' => '+256'],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'dialing_code' => '+380'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'dialing_code' => '+971'],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'dialing_code' => '+44'],
            ['name' => 'United States', 'iso_code' => 'US', 'dialing_code' => '+1'],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'dialing_code' => '+598'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZ', 'dialing_code' => '+998'],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'dialing_code' => '+678'],
            ['name' => 'Vatican City', 'iso_code' => 'VA', 'dialing_code' => '+379'],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'dialing_code' => '+58'],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'dialing_code' => '+84'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'dialing_code' => '+967'],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'dialing_code' => '+260'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'dialing_code' => '+263'],
        ];

        DB::table('countries')->insert($countries);
    }
}
