<?php

declare(strict_types=1);

namespace App\Services\Accounting;

use App\Exceptions\Accounting\AccountValidationException;
use App\Models\Account;
use App\Models\Agent;
use App\Models\Branch;
use App\Models\Client;
use App\Models\Supplier;
use App\Models\SupplierCompany;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

/**
 * The ONLY way to create an account (MF-1). Enforces the blueprint's nine COA rules and is
 * backstopped by App\Observers\AccountObserver's `creating` hook (flag-gated on its own
 * independent config('accounting.account_observer.enabled') — see that class's own docblock for
 * the round-4 fix that decoupled it from config('accounting.engine.enabled'), and NOT the flat
 * 'accounting.posting_engine_enabled' string an earlier task brief named) so imports/tinker
 * cannot bypass it once that flag is turned on (P2+, after the legacy call sites below are
 * migrated onto this service).
 *
 * File 11 §P1.0, L150-173, verbatim contract for the two public methods.
 */
final class AccountService
{
    /** Depth ceiling: a root is level 1, so level may range 1..6. */
    private const MAX_DEPTH = 6;

    /** The only account names allowed to be created with no parent_id (CoaSeeder's level-1 rows). */
    private const FIXED_ROOT_NAMES = ['Assets', 'Liabilities', 'Equity', 'Income', 'Expenses'];

    private const PENDING_CODE = 'PENDING';

    /**
     * @internal Set true only while this service's own save() calls are in flight, so
     *           App\Observers\AccountObserver can tell "a write that went through AccountService"
     *           apart from every other Account::create()/save() call site in the app. Never set
     *           this outside this class.
     */
    public static bool $creatingViaService = false;

    public function __construct(
        private readonly AccountCodeGenerator $codes,
        private readonly AccountResolver $resolver,
    ) {}

    /**
     * Enforces the blueprint's nine rules:
     *  1. parent mandatory, except the fixed roots (Assets/Liabilities/Equity/Income/Expenses).
     *  2. depth <= 6.
     *  3. level = parent.level + 1 (1 for a root).
     *  4. no mixed parents: an account cannot remain a valid posting leaf (is_group=false) once
     *     it gains a child — the instant a new account is created under it, that parent is
     *     promoted to is_group=true in the same transaction, so "leaf with children" never
     *     exists for anything that goes through this service.
     *  5. root_id derived from the resolved root, never taken from $attrs.
     *  6. account_type derived from the resolved root's name, never taken from $attrs.
     *  7. code generated by AccountCodeGenerator, never taken from $attrs.
     *  8. is_group = false at birth, never taken from $attrs.
     *  9. company scope: $attrs['company_id'] (or the authenticated user's resolved company) is
     *     the single source of truth; an explicit parent_id belonging to a different company is
     *     rejected outright.
     */
    public function create(array $attrs): Account
    {
        $name = trim((string) ($attrs['name'] ?? ''));

        if ($name === '') {
            throw new AccountValidationException('AccountService::create() requires a non-empty "name".');
        }

        return DB::transaction(function () use ($attrs, $name) {
            $companyId = $this->resolveCompanyId($attrs);
            $parent = $this->resolveParent($attrs, $companyId);

            // MEDIUM finding fix (AccountCodeGenerator re-introduces the BUG-H1 race): generate()
            // below is a plain read-then-write max(sibling code) scan with no locking of its own,
            // so two concurrent create() calls under the SAME parent can both read the same max
            // and both write the same code (system_accounts has no unique(company_id, code) yet —
            // deferred). Re-fetching $parent with lockForUpdate() here serializes any concurrent
            // create() under this parent for the rest of this transaction, closing that window;
            // every other use of $parent below (level, root, is_group promotion) is unaffected
            // since it is the same row, just now held under lock.
            if ($parent !== null) {
                $lockedParent = Account::query()->withoutGlobalScopes()->lockForUpdate()->find($parent->id);

                // P1 FIX ROUND 3 (LOW finding fix): resolveParent() above already loaded and
                // validated $parent (existence + same-tenant) moments earlier, outside any lock.
                // If it has since vanished — concurrently deleted between that read and this
                // lockForUpdate() re-fetch — the old code silently fell through with $parent still
                // null, which every branch below reads as "no parent_id was ever given," i.e. a
                // root-creation request: it skips assertCanCreateRoot() entirely (that call only
                // lives in the `else` branch), so an arbitrary child name could be persisted as an
                // unvalidated level-1 root with root_id=null and account_type set to its own name.
                // A vanished parent is a genuine race, not "no parent was requested" — refuse
                // instead of reinterpreting the request.
                if ($lockedParent === null) {
                    throw new AccountValidationException(sprintf(
                        'parent_id=%d existed when this request started but no longer does — it was '
                        .'deleted concurrently. Retry the request.',
                        $parent->id
                    ));
                }

                $parent = $lockedParent;
            } else {
                // No parent means this create() is creating one of the 5 fixed roots. There is no
                // parent row to lock, so serialize on the company itself (advisory lock keyed on
                // company_id) to close the same race for concurrent root creation. Best-effort: if
                // the company row does not exist (shouldn't happen — resolveCompanyId already
                // produced this id), there is nothing to lock and root creation proceeds exactly
                // as it did before this fix.
                DB::table('companies')->where('id', $companyId)->lockForUpdate()->first();

                $this->assertCanCreateRoot($name, $companyId);
            }

            $level = $parent !== null ? $parent->level + 1 : 1;

            if ($level > self::MAX_DEPTH) {
                throw new AccountValidationException(sprintf(
                    'Creating "%s" under parent_id=%s would put it at depth %d, exceeding the maximum of %d.',
                    $name,
                    $parent?->id !== null ? (string) $parent->id : 'null',
                    $level,
                    self::MAX_DEPTH
                ));
            }

            $root = $this->resolveRoot($parent);
            $accountType = $root !== null ? $root->name : $name;
            $reportType = $attrs['report_type']
                ?? $root?->report_type
                ?? $parent?->report_type
                ?? Account::REPORT_TYPES['BALANCE_SHEET'];

            $actorId = $attrs['created_by'] ?? (Auth::check() ? Auth::id() : null);

            $account = new Account;
            $account->name = $name;
            $account->parent_id = $parent?->id;
            $account->root_id = $root?->id;
            $account->account_type = $accountType;
            $account->report_type = $reportType;
            $account->level = $level;
            $account->company_id = $companyId;
            $account->is_group = false;
            $account->disabled = (bool) ($attrs['disabled'] ?? false);
            $account->serial_number = $attrs['serial_number'] ?? null;
            $account->branch_id = $attrs['branch_id'] ?? null;
            $account->agent_id = $attrs['agent_id'] ?? null;
            $account->client_id = $attrs['client_id'] ?? null;
            $account->supplier_id = $attrs['supplier_id'] ?? null;
            $account->supplier_company_id = $attrs['supplier_company_id'] ?? null;
            $account->reference_id = $attrs['reference_id'] ?? null;
            $account->currency = $attrs['currency'] ?? 'KWD';
            $account->balance_must_be = $attrs['balance_must_be'] ?? null;
            $account->actual_balance = $attrs['actual_balance'] ?? 0;
            $account->opening_balance = $attrs['opening_balance'] ?? 0;
            $account->opening_balance_date = $attrs['opening_balance_date'] ?? null;
            $account->budget_balance = $attrs['budget_balance'] ?? 0;
            $account->variance = $attrs['variance'] ?? 0;
            $account->created_by = $actorId;
            $account->updated_by = $actorId;

            $generatedCode = $this->codes->generate($parent, $companyId);
            $account->code = $generatedCode ?? self::PENDING_CODE;

            self::$creatingViaService = true;
            try {
                $account->save();

                if ($generatedCode === null) {
                    // BUG-H1 row-id fallback: no numeric sibling to extend from, so the newly
                    // persisted row's own id becomes its code.
                    $account->code = $this->codes->fallbackCode($account);
                    $account->save();
                }

                if ($parent !== null && ! $parent->is_group) {
                    $parent->is_group = true;
                    $parent->updated_by = $actorId;
                    $parent->save();
                }
            } finally {
                self::$creatingViaService = false;
            }

            return $account->refresh();
        });
    }

    /**
     * Auto-create (idempotently) the per-party leaf under the account system_accounts maps
     * $purposeCode to for $companyId. Reuses the working AgentController tree pattern
     * (AgentController.php:449-666: leaf under a fixed anchor group, level = anchor.level + 1,
     * one row per party), but — unlike that legacy code — derives root_id/account_type from the
     * anchor's resolved root via create() above instead of copying the anchor's own (possibly
     * null/legacy) account_type straight across.
     */
    public function ensurePartyLeaf(string $purposeCode, Model $party, int $companyId): Account
    {
        return DB::transaction(function () use ($purposeCode, $party, $companyId) {
            $anchor = $this->resolver->resolve($purposeCode, $companyId);

            [$column, $partyId] = $this->partyDiscriminator($party);

            $existing = Account::query()
                ->withoutGlobalScopes()
                ->where('company_id', $companyId)
                ->where('parent_id', $anchor->id)
                ->where($column, $partyId)
                ->first();

            if ($existing !== null) {
                return $existing;
            }

            // HIGH finding fix: AccountResolver::resolve() only ever hands back a leaf that
            // system_accounts is CURRENTLY using as a direct posting target for $purposeCode
            // (that is what "resolve by purpose code" means). create()'s rule 4 promotes $anchor
            // to is_group = true the instant its first child lands — which is exactly what the
            // lines below are about to do. Doing that here would silently turn the very account
            // this call just resolved into a non-leaf, so every future
            // LineDraft(purposeCode: $purposeCode) would throw NonLeafAccountException from then
            // on: this method would have destroyed the mapping it depends on. Refuse instead of
            // guessing — see assertAnchorIsSafeToExpand() docblock.
            $this->assertAnchorIsSafeToExpand($anchor, $companyId, $purposeCode);

            return $this->create([
                'company_id' => $companyId,
                'parent_id' => $anchor->id,
                'name' => $this->partyName($party),
                $column => $partyId,
            ]);
        });
    }

    /**
     * Guards the corruption described in ensurePartyLeaf()'s call site comment above. A leaf that
     * system_accounts is still using as a direct posting target must never be demoted to a group
     * by this method.
     *
     * P1 FIX ROUND 3 (MEDIUM regression fix): this used to also treat `is_group=true` as proof
     * that "some earlier, deliberate step already promoted this account, so it's provably no
     * longer anyone's live posting-target leaf." That reasoning was never sound, and pairing it
     * with AccountResolver::resolve()'s OWN leaf guarantee made it actively self-defeating in two
     * different ways depending on what resolve() itself trusted:
     *   - While resolve() also rejected is_group=true (ROUND 2), no anchor reaching this method
     *     could ever have is_group=true — resolve() would have thrown NonLeafAccountException
     *     first. The is_group half of the old check was therefore dead code: this method threw
     *     unconditionally and its escape hatch could never execute (verification: MEDIUM finding,
     *     this round).
     *   - Now that resolve() correctly stops trusting is_group (AccountResolver::isLeaf(), the
     *     HIGH regression fix above), an anchor with the same TRUE default is_group has almost
     *     everywhere (~42,401 accounts, per that method's docblock) but zero children CAN reach
     *     this method — and the old check would have silently read that stale default as "already
     *     promoted, safe to expand," letting a live posting target for real customer data be
     *     demoted to a group with no warning. That is precisely the corruption this method exists
     *     to prevent.
     * Fix: is_group is never consulted here either, matching AccountResolver::isLeaf()'s rule —
     * one leaf definition for the whole engine, not two that can silently disagree depending on
     * what a caller upstream happened to already filter.
     *
     * With is_group gone, the only two questions left are the ones this method's name promises:
     * is $anchor still a leaf (re-checked defensively — resolve() above already guarantees this
     * within the same transaction, but re-deriving it from the DB rather than trusting that
     * invariant across the call boundary costs one query and closes the door on a future refactor
     * silently breaking the guarantee), and is it a live system_accounts posting target for this
     * company (for ANY purpose code, not only $purposeCode, since adding a child here would break
     * every purpose code pointing at it identically).
     *
     * P1 ships no purpose code dedicated purely to anchoring a per-party group — every purpose
     * code SystemAccountsSeeder maps today (RECEIVABLE_CONTROL, PAYABLE_CONTROL, ...) resolves
     * directly to the pooled posting-target leaf itself, so both questions above answer "yes" for
     * every account this method will ever see today and it refuses loudly, always — intentional,
     * not a bug (see resolve()'s own guarantee above: it is structurally impossible for
     * $isPostingTarget to be false right now, since that is exactly how $anchor was found).
     * De-pooling a leaf into a proper per-party tree needs a distinct anchor purpose code,
     * separate from the control one (Accounting Gap/13-party-ledger-reattribution-plan.md §B:
     * RECEIVABLE_CONTROL_LEGACY vs RECEIVABLE_PARTY_GROUP) plus a migration that moves history
     * onto the new leaves — that design and its call sites are explicitly P2 scope (mission rule
     * 3), not invented here. The method needs no further change for that day: the moment a
     * purpose code resolves to an anchor that system_accounts does not ALSO list as a direct
     * posting target, $isPostingTarget naturally evaluates false and this method starts allowing
     * the expansion — its "escape hatch" is real, just correctly unreachable under P1's current
     * vocabulary rather than unreachable by accident.
     *
     * @throws AccountValidationException when $anchor is still a leaf that system_accounts maps
     *                                    as a posting target for this company.
     */
    private function assertAnchorIsSafeToExpand(Account $anchor, int $companyId, string $purposeCode): void
    {
        if (! AccountResolver::isLeaf($anchor)) {
            return;
        }

        $isPostingTarget = DB::table('system_accounts')
            ->where('company_id', $companyId)
            ->where('account_id', $anchor->id)
            ->exists();

        if ($isPostingTarget) {
            throw new AccountValidationException(sprintf(
                'ensurePartyLeaf() refuses to add a child under account #%d (%s): it is still a leaf '
                .'that system_accounts maps as a direct posting target for company_id=%d (resolved via '
                .'purpose_code=%s). Promoting it to a group here would silently break every future '
                .'posting to that purpose code. De-pooling this account requires a dedicated per-party '
                .'anchor purpose code, distinct from the control one (see '
                .'Accounting Gap/13-party-ledger-reattribution-plan.md §B) — that is P2 scope.',
                $anchor->id,
                $anchor->name,
                $companyId,
                $purposeCode
            ));
        }
    }

    private function resolveCompanyId(array $attrs): int
    {
        if (isset($attrs['company_id'])) {
            return (int) $attrs['company_id'];
        }

        if (Auth::check() && function_exists('getCompanyId')) {
            $resolved = getCompanyId(Auth::user());
            if ($resolved !== null) {
                return (int) $resolved;
            }
        }

        throw new AccountValidationException(
            'AccountService::create() requires an explicit "company_id" (none was given and none could be resolved from the authenticated user).'
        );
    }

    private function resolveParent(array $attrs, int $companyId): ?Account
    {
        $parentId = $attrs['parent_id'] ?? null;

        if ($parentId === null) {
            return null;
        }

        $parent = Account::query()->withoutGlobalScopes()->find((int) $parentId);

        if ($parent === null) {
            throw new AccountValidationException("parent_id={$parentId} does not exist.");
        }

        if ((int) $parent->company_id !== $companyId) {
            throw new AccountValidationException(sprintf(
                'parent_id=%d belongs to company_id=%d but this account is being created for company_id=%d.',
                $parent->id,
                $parent->company_id,
                $companyId
            ));
        }

        return $parent;
    }

    private function resolveRoot(?Account $parent): ?Account
    {
        if ($parent === null) {
            // This create() call IS creating a root: it has no root above it.
            return null;
        }

        if ($parent->parent_id === null) {
            // The parent is itself a fixed root.
            return $parent;
        }

        if ($parent->root_id === null) {
            throw new AccountValidationException("Account #{$parent->id} has a parent_id but no root_id — the tree above it is corrupt.");
        }

        $root = Account::query()->withoutGlobalScopes()->find($parent->root_id);

        if ($root === null) {
            throw new AccountValidationException("Account #{$parent->id}'s root_id={$parent->root_id} does not exist.");
        }

        return $root;
    }

    private function assertCanCreateRoot(string $name, int $companyId): void
    {
        if (! in_array($name, self::FIXED_ROOT_NAMES, true)) {
            throw new AccountValidationException(sprintf(
                'parent_id is required unless creating one of the fixed root accounts (%s); got name="%s" with no parent_id.',
                implode(', ', self::FIXED_ROOT_NAMES),
                $name
            ));
        }

        $exists = Account::query()
            ->withoutGlobalScopes()
            ->where('company_id', $companyId)
            ->whereNull('parent_id')
            ->where('name', $name)
            ->exists();

        if ($exists) {
            throw new AccountValidationException("A root account named \"{$name}\" already exists for company_id={$companyId}.");
        }
    }

    /** @return array{0: string, 1: int|string} [accounts column, party key] */
    private function partyDiscriminator(Model $party): array
    {
        return match (true) {
            $party instanceof Agent => ['agent_id', $party->getKey()],
            $party instanceof Client => ['client_id', $party->getKey()],
            $party instanceof Supplier => ['supplier_id', $party->getKey()],
            $party instanceof SupplierCompany => ['supplier_company_id', $party->getKey()],
            $party instanceof Branch => ['branch_id', $party->getKey()],
            default => throw new AccountValidationException(sprintf(
                'ensurePartyLeaf() does not know which accounts column anchors a party of type %s.',
                get_class($party)
            )),
        };
    }

    private function partyName(Model $party): string
    {
        $name = data_get($party, 'name');

        if (is_string($name) && trim($name) !== '') {
            return trim($name);
        }

        return sprintf('%s #%s', class_basename($party), (string) $party->getKey());
    }
}
