<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Part of the P0 launch hotfixes (HF-4 / HF-5): the application-level fix
 * (Sequence::lockForUpdate() claim / Payment::lockForUpdate() completion guard — see the
 * "Accounting Gap" hotfix HF-4/HF-5 notes) closes the *race window* on `payments`, but a
 * unique index is the database-level backstop that makes a duplicate voucher number
 * impossible even if a future code path reintroduces the race.
 *
 * SCOPE CHANGE (2026-08-3x, production-shaped-data analysis against `akeed_verify_snapshot`):
 * this migration ORIGINALLY also created a second unique index, on
 * `transactions(payment_id, reference_type)`, in this same up(). Two problems, discovered by
 * running this migration against real CT-shaped data rather than a synthetic fixture:
 *
 *   1. NOT PARTIAL-FAILURE-SAFE. MySQL DDL statements implicit-commit one at a time. On the
 *      analysis DB the `payments` index below landed, then the `transactions` index failed —
 *      leaving the migration half-applied with NO row recorded in the `migrations` table (the
 *      whole batch is considered failed), and no idempotency guard, so simply re-running it
 *      tripped "Duplicate key name" on the `payments` index it had already created. A single
 *      up() spanning two DDLs on two different tables cannot be made atomic in MySQL, so it
 *      must not promise atomicity it cannot deliver.
 *   2. THE TRANSACTIONS HALF WAS WRONG FOR REAL DATA. CT's actual `transactions` table
 *      violates a raw `(payment_id, reference_type)` uniqueness constraint 2,007 times over its
 *      real history. 98% of those are a notification-row-vs-ledger-row design collision in the
 *      MyFatoorah top-up flow (two legitimate, differently-purposed rows legitimately sharing
 *      the same `payment_id`/`reference_type` pair) — NOT double money movement. Only 2 are
 *      genuine GL double-posts, and both are already Suspense-balanced. A raw two-column unique
 *      index can never be applied to this table's history as-is, and the race it is meant to
 *      close is still live in production (~20 new collisions/month), so simply dropping the
 *      idea isn't acceptable either.
 *
 * RESOLUTION: this migration now does ONLY the `payments` half — guarded so a rerun, or a
 * rerun after exactly the partial-failure shape above (index present, no `migrations` row), is
 * always a safe no-op. The `transactions` half moves to migration
 * 2026_08_24_000002_add_post_cutover_dedup_key_to_transactions_table.php, which enforces
 * uniqueness only on POST-CUTOVER rows via a nullable STORED generated column (see that
 * migration's own docblock for the full reasoning) — leaving historic rows deliberately
 * un-migrated rather than mutating them.
 *
 * DO NOT run this migration until the `payments` data has been audited for existing
 * duplicates under this key (e.g.
 *   SELECT company_id, voucher_number, COUNT(*) FROM payments
 *     GROUP BY company_id, voucher_number HAVING COUNT(*) > 1;
 * ) -- adding a unique index over rows that already violate it will fail the migration
 * outright. See "Accounting Gap" hotfix HF-4/HF-5 notes.
 */
return new class extends Migration
{
    /**
     * The exact name Laravel's schema builder is given for
     * `$table->unique(['company_id', 'voucher_number'])` on `payments` — explicit, not
     * autogenerated, so it is stable across reruns and across environments.
     */
    private const INDEX_NAME = 'payments_company_id_voucher_number_unique';

    /**
     * Run the migrations.
     *
     * Idempotency guard via Schema::hasIndex() (confirmed present on this Laravel version —
     * v11.39.1, Illuminate\Database\Schema\Builder::hasIndex(); no raw SHOW INDEX fallback
     * needed). Makes up() a safe no-op both on a clean rerun and on the specific partial-failure
     * shape that motivated this rewrite: the index already exists on disk but the `migrations`
     * table has no row for this file (because the ORIGINAL two-DDL up() failed on its second
     * statement, on a different table, before ever completing).
     */
    public function up(): void
    {
        if (Schema::hasIndex('payments', self::INDEX_NAME)) {
            return;
        }

        Schema::table('payments', function (Blueprint $table) {
            // A voucher number only needs to be unique within a company (each
            // company's sequence starts at 1), so the index is composite.
            $table->unique(['company_id', 'voucher_number'], self::INDEX_NAME);
        });
    }

    /**
     * Reverse the migrations.
     *
     * Symmetric guard: only drops the index if it is actually present, so `migrate:rollback`
     * is equally safe to run twice or against a partially-applied state.
     */
    public function down(): void
    {
        if (! Schema::hasIndex('payments', self::INDEX_NAME)) {
            return;
        }

        Schema::table('payments', function (Blueprint $table) {
            $table->dropUnique(self::INDEX_NAME);
        });
    }
};
