<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the dotw_prebooks table.
 *
 * This table is the header record for a DOTW B2C hotel pre-booking session.
 * Each row represents a rate that a customer has selected and locked, before
 * payment is confirmed. On payment success, a corresponding hotel_bookings row
 * and Task are created, and this record is updated with the supplier status.
 *
 * The table is created only when the AkeedDotwAI module is enabled
 * (AKEED_DOTWAI_ENABLED=true), because the ServiceProvider gates
 * loadMigrationsFrom() on that flag.
 *
 * FK targets:
 *  - clients          (core table, always present)
 *  - hotel_bookings   (core table, always present)
 *  - payments         (core table, always present)
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('dotw_prebooks', function (Blueprint $table) {
            $table->id();

            // Unique token generated by the module in PB-XXXXXXXX format.
            // Max 32 chars to accommodate format with prefix.
            $table->string('prebook_key', 32)->unique();

            // Retained for skill compatibility; this module is B2C-only.
            $table->enum('booking_type', ['b2b', 'b2c'])->default('b2c');

            // Set after passport intake + Client creation.
            $table->unsignedBigInteger('client_id')->nullable();
            $table->foreign('client_id')
                ->references('id')
                ->on('clients')
                ->nullOnDelete();

            // E.164-normalised customer phone — primary session identifier.
            $table->string('customer_phone');
            $table->index('customer_phone');

            // Hotel identifiers from DOTW search response.
            $table->string('hotel_id');
            $table->string('hotel_name');
            $table->string('city_code');

            // Stay dates.
            $table->date('check_in');
            $table->date('check_out');

            // Rate identifiers from DOTW prebook response.
            $table->string('room_type_code');
            $table->string('rate_basis_id');
            $table->string('rate_basis_desc');
            $table->text('allocation_details');

            // Pricing — original fare from supplier.
            $table->decimal('original_total_fare', 12, 3);
            $table->string('original_currency', 8);

            // Pricing — after markup computation.
            $table->decimal('price_before_markup', 12, 3);
            $table->decimal('total_fare', 12, 3);
            $table->string('currency', 8);

            // Markup ratio stored as a fraction (e.g. 0.1200 = 12 %).
            $table->decimal('markup_percentage', 5, 4);

            // Supplier-supplied policy text; nullable (not always present).
            $table->text('tariff_notes')->nullable();

            // Structured cancellation rules from DOTW response.
            $table->json('cancellation_rules');

            // Optional room specials / meal plan descriptors.
            $table->json('specials')->nullable();

            // Rate flags.
            $table->boolean('is_refundable');
            $table->boolean('is_apr')->default(false);

            // Minimum-stay constraint (if any).
            $table->integer('min_stay')->nullable();
            $table->date('min_stay_date')->nullable();

            // Changed-occupancy payload from DOTW when room count differs
            // from what the customer searched (e.g. split rooms).
            $table->json('changed_occupancy')->nullable();

            // Guest nationality/residence codes used in the search query.
            $table->string('nationality_code', 8);
            $table->string('residence_code', 8);

            // Linked booking record — populated after confirmBooking succeeds.
            $table->unsignedBigInteger('hotel_booking_id')->nullable();
            $table->foreign('hotel_booking_id')
                ->references('id')
                ->on('hotel_bookings')
                ->nullOnDelete();

            // Supplier confirmation numbers — populated after confirmBooking.
            $table->string('confirmation_no')->nullable();
            $table->string('booking_ref')->nullable();

            // Linked payment record.
            $table->unsignedBigInteger('payment_id')->nullable();
            $table->foreign('payment_id')
                ->references('id')
                ->on('payments')
                ->nullOnDelete();

            // Payment lifecycle status.
            $table->enum('payment_status', ['pending', 'paid', 'failed', 'refunded'])->nullable();

            // Supplier-side booking status.
            $table->enum('supplier_status', ['confirmed', 'failed', 'cancelled'])->nullable();

            // Free-text field from supplier guaranteeing payment terms.
            $table->text('payment_guaranteed_by')->nullable();

            // Rate-lock TTL — used by the cleanup cron and for UI countdown.
            $table->dateTime('expires_at');
            $table->index('expires_at', 'dotw_prebooks_expires_idx');

            $table->timestamps();

            // Composite index for session lookup by phone + payment state.
            $table->index(
                ['customer_phone', 'payment_status'],
                'dotw_prebooks_phone_status_idx'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('dotw_prebooks');
    }
};
