name: Deploy to cPanel

on:
  push:
    branches:
      - dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'  

    - name: Install dependencies
      run: npm install
      
    - name: Build assets
      run: npm run build
    
    - name: Configure PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, curl, json, zip, gd, fileinfo, bcmath, intl, openssl, xml
    
    # - name: Install Composer dependencies
    #   run: composer install --no-dev --optimize-autoloader --prefer-dist

    - name: Create deployment artifact
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
    
    - name: Store artifact for distribution
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: ${{ github.sha}}.tar.gz

    - name: Deploy to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        local-dir: ./  # Path to your build output
        server: ${{ secrets.FTP_STAGING_SERVER }}
        username: ${{ secrets.FTP_STAGING_USERNAME }}
        password: ${{ secrets.FTP_STAGING_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        protocol: 'ftp'  # or 'sftp' if you're using SFTP

    - name: Generate version.json
      run: |
        echo "{ \"commit\": \"$(git rev-parse --short HEAD)\", \"branch\": \"$(git rev-parse --abbrev-ref HEAD)\", \"date\": \"$(git log -1 --format=%ci)\" }" > public/version.json